name: Package and Release

on:
  push:
    tags:
      - '**'
    branches:
      - alpha

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
  DISCORD_WEBHOOK: https://discord.com/api/webhooks/1404939800921899048/rZZbVLou6M4kqNuCIwYPcNDK9W_qRC5duF-xXgBgmSxf5TU--sYfOEO14LOLDB3g1_JJ

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "donniedice"
          git config --global user.email "donniedice@protonmail.com"
          
      - name: Set Release Type
        id: set_release_type
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME=${{ github.ref }}
            if [[ "$TAG_NAME" == *"beta"* ]]; then
              echo "release_type=beta" >> $GITHUB_OUTPUT
            elif [[ "$TAG_NAME" == *"alpha"* ]]; then
              echo "release_type=alpha" >> $GITHUB_OUTPUT
            else
              echo "release_type=release" >> $GITHUB_OUTPUT
            fi
          else
            echo "release_type=alpha" >> $GITHUB_OUTPUT
          fi

      - name: Extract Version from TOC
        id: extract_version
        run: |
          version=$(grep -oP '^## Version: \K(.*)' ./*.toc)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "timestamp=$(date -u +%Y-%m-%dT%H:%M:%S.000Z)" >> $GITHUB_OUTPUT

      - name: Extract Changelog
        id: extract_changelog
        run: |
          if [ -f "docs/CHANGES.md" ]; then
            # Extract only the most recent version's changelog (everything between first ## and second ##)
            CHANGELOG=$(awk '/^## v[0-9]/{if(NR>1)exit;next} NR>1' docs/CHANGES.md | sed '/^$/d' | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
            echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT
          else
            echo "changelog=No changelog available" >> $GITHUB_OUTPUT
          fi

      - name: Package and Release
        uses: BigWigsMods/packager@master
        with:
          release-type: ${{ steps.set_release_type.outputs.release_type }}

      - name: Send Discord Success Notification
        if: success() && steps.set_release_type.outputs.release_type == 'release'
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"username\": \"CCU Update\",
              \"avatar_url\": \"https://raw.githubusercontent.com/DonnieDice/CoordinationCloakUtility/main/images/icon.png\",
              \"embeds\": [{
                \"title\": \"🎉 CCU | Coordination Cloak Utility - ${{ steps.extract_version.outputs.version }}\",
                \"description\": \"**Teleport with ease!** A new version of CCU has been released!\\n\\n🎵 **What's New:**\\n${{ steps.extract_changelog.outputs.changelog }}\",
                \"url\": \"https://github.com/DonnieDice/CoordinationCloakUtility/releases/tag/${{ github.ref_name }}\",
                \"color\": 9830721,
                \"thumbnail\": {
                  \"url\": \"https://raw.githubusercontent.com/DonnieDice/CoordinationCloakUtility/main/images/icon.png\"
                },
                \"fields\": [
                  {
                    \"name\": \"📥 Downloads\",
                    \"value\": \"[CurseForge](https://www.curseforge.com/wow/addons/ccu-coordination-cloak-utility)\\n[Wago.io](https://addons.wago.io/addons/coordinationcloakutility)\\n[GitHub](https://github.com/DonnieDice/CoordinationCloakUtility)\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"🎮 Compatibility\",
                    \"value\": \"✅ The War Within\\n✅ Dragonflight\\n✅ Classic Era\\n✅ Cataclysm\",
                    \"inline\": true
                  },
                  {
                    \"name\": \"💬 Support\",
                    \"value\": \"[Report Issues](https://github.com/DonnieDice/CoordinationCloakUtility/issues)\\n[Buy Me Coffee](https://www.buymeacoffee.com/donniedice)\",
                    \"inline\": true
                  }
                ],
                \"footer\": {
                  \"text\": \"RGX Mods - RealmGX Community\",
                  \"icon_url\": \"https://raw.githubusercontent.com/donniedice/SimpleQuestPlates/main/images/kiwi.gif\"
                },
                \"timestamp\": \"${{ steps.extract_version.outputs.timestamp }}\"
              }]
            }" https://discord.com/api/webhooks/1404939800921899048/rZZbVLou6M4kqNuCIwYPcNDK9W_qRC5duF-xXgBgmSxf5TU--sYfOEO14LOLDB3g1_JJ

      - name: Send Discord Beta Notification
        if: success() && steps.set_release_type.outputs.release_type == 'beta'
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"username\": \"CCU Beta\",
              \"avatar_url\": \"https://raw.githubusercontent.com/DonnieDice/CoordinationCloakUtility/main/images/icon.png\",
              \"embeds\": [{
                \"title\": \"🧪 CCU Beta - ${{ steps.extract_version.outputs.version }}\",
                \"description\": \"A beta version of Coordination Cloak Utility is available for testing!\\n\\n**What's New:**\\n${{ steps.extract_changelog.outputs.changelog }}\",
                \"color\": 16744448,
                \"fields\": [
                  {
                    \"name\": \"📥 Download Beta\",
                    \"value\": \"[CurseForge](https://www.curseforge.com/wow/addons/ccu-coordination-cloak-utility)\\n[GitHub](https://github.com/DonnieDice/CoordinationCloakUtility/releases)\"
                  }
                ],
                \"footer\": {
                  \"text\": \"RGX Mods - Beta Build\",
                  \"icon_url\": \"https://raw.githubusercontent.com/donniedice/SimpleQuestPlates/main/images/kiwi.gif\"
                },
                \"timestamp\": \"${{ steps.extract_version.outputs.timestamp }}\"
              }]
            }" https://discord.com/api/webhooks/1404939800921899048/rZZbVLou6M4kqNuCIwYPcNDK9W_qRC5duF-xXgBgmSxf5TU--sYfOEO14LOLDB3g1_JJ

      - name: Send Discord Alpha Notification
        if: success() && steps.set_release_type.outputs.release_type == 'alpha'
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"username\": \"CCU Alpha\",
              \"avatar_url\": \"https://raw.githubusercontent.com/DonnieDice/CoordinationCloakUtility/main/images/icon.png\",
              \"embeds\": [{
                \"title\": \"🔬 CCU Alpha - ${{ steps.extract_version.outputs.version }}\",
                \"description\": \"Development build for testing\\n\\n**What's New:**\\n${{ steps.extract_changelog.outputs.changelog }}\",
                \"color\": 16711680,
                \"footer\": {
                  \"text\": \"RGX Mods - Alpha Build\",
                  \"icon_url\": \"https://raw.githubusercontent.com/donniedice/SimpleQuestPlates/main/images/kiwi.gif\"
                },
                \"timestamp\": \"${{ steps.extract_version.outputs.timestamp }}\"
              }]
            }" https://discord.com/api/webhooks/1404939800921899048/rZZbVLou6M4kqNuCIwYPcNDK9W_qRC5duF-xXgBgmSxf5TU--sYfOEO14LOLDB3g1_JJ

      - name: Send Discord Failure Notification
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "username": "CCU Build Failed",
              "avatar_url": "https://raw.githubusercontent.com/DonnieDice/CoordinationCloakUtility/main/images/icon.png",
              "embeds": [{
                "title": "❌ CCU Build Failed",
                "description": "The release workflow encountered an error",
                "url": "https://github.com/DonnieDice/CoordinationCloakUtility/actions/runs/${{ github.run_id }}",
                "color": 15158332,
                "fields": [
                  {
                    "name": "Version",
                    "value": "${{ steps.extract_version.outputs.version || 'Unknown' }}",
                    "inline": true
                  },
                  {
                    "name": "Workflow",
                    "value": "[View Logs](https://github.com/DonnieDice/CoordinationCloakUtility/actions/runs/${{ github.run_id }})",
                    "inline": true
                  }
                ],
                "footer": {
                  "text": "RGX Mods - Build System",
                  "icon_url": "https://raw.githubusercontent.com/donniedice/SimpleQuestPlates/main/images/kiwi.gif"
                },
                "timestamp": "${{ steps.extract_version.outputs.timestamp }}"
              }]
            }' https://discord.com/api/webhooks/1404939800921899048/rZZbVLou6M4kqNuCIwYPcNDK9W_qRC5duF-xXgBgmSxf5TU--sYfOEO14LOLDB3g1_JJ

      - name: Parse Changelog
        if: ${{ steps.set_release_type.outputs.release_type != 'alpha' }}
        run: |
          # Your existing changelog parsing logic
