name: Package and Release

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0, v1.0.0-alpha, etc.

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Correct the name if needed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "donniedice"
          git config --global user.email "donniedice@protonmail.com"

      - name: Set Release Type
        id: set_release_type
        run: |
          TAG_NAME=${{ github.ref }}
          if [[ "$TAG_NAME" == *"beta"* ]]; then
            echo "release_type=beta" >> $GITHUB_ENV
          elif [[ "$TAG_NAME" == *"alpha"* ]]; then
            echo "release_type=alpha" >> $GITHUB_ENV
          else
            echo "release_type=release" >> $GITHUB_ENV
          fi

      - name: Extract Version from TOC
        id: extract_version
        run: |
          version=$(grep -oP '^## Version: \K(.*)' ./*.toc)
          echo "version=$version" >> $GITHUB_ENV

      - name: Package and Release
        uses: BigWigsMods/packager@master
        with:
          release-type: ${{ env.release_type }}

      - name: Parse Changelog
        if: ${{ env.release_type != 'alpha' }}
        run: |
          # Your existing changelog parsing logic
